// AUTH
export const FETCH_AUTH = 'FETCH_AUTH'
export const RECEIVE_AUTH = 'RECEIVE_AUTH'
export const FAILED_AUTH = 'FAILED_AUTH'
export const FETCH_LOGOUT_USER = 'FETCH_LOGOUT_USER'

// ACCOUNT UPDATE
export const FETCH_CHANGE_ACCOUNT = 'FETCH_CHANGE_ACCOUNT'
export const RECEIVE_CHANGE_ACCOUNT = 'RECEIVE_CHANGE_ACCOUNT'
export const FAILED_CHANGE_ACCOUNT = 'FAILED_CHANGE_ACCOUNT'

// FORGOT PASSWORD
export const FETCH_FORGOT_PASSWORD = 'FETCH_FORGOT_PASSWORD'
export const RECEIVE_ITEM_FORGOT_PASSWORD = 'RECEIVE_ITEM_FORGOT_PASSWORD'
export const FAILED_FORGOT_PASSWORD = 'FAILED_FORGOT_PASSWORD'

// IMAGE
export const FETCH_IMAGE = 'FETCH_IMAGE'
export const SUCCESS_IMAGE = 'SUCCESS_IMAGE'
export const FAILED_IMAGE = 'FAILED_IMAGE'

// CURRENT TIME
export const FETCH_CURRENT_TIME = 'FETCH_CURRENT_TIME'
export const FAILED_CURRENT_TIME = 'FAILED_CURRENT_TIME'
export const RECEIVE_CURRENT_TIME = 'RECEIVE_CURRENT_TIME'

// USER
export const FETCH_USER = 'FETCH_USER'
export const FAILED_USER = 'FAILED_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_ITEM_USER = 'RECEIVE_ITEM_USER'

// VERIFICATION
export const FETCH_VERIFICATION = 'FETCH_VERIFICATION'
export const SUCCESS_VERIFICATION = 'SUCCESS_VERIFICATION'
export const FAILED_VERIFICATION = 'FAILED_VERIFICATION'

// RESET PASSWORD
export const FETCH_RESET_PASSWORD = 'FETCH_RESET_PASSWORD'
export const SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD'
export const FAILED_RESET_PASSWORD = 'FAILED_RESET_PASSWORD'

// GENERATED TYPES
